In [197]:
import pandas as pd
import numpy as np
import os

In [198]:
filename1 = os.path.join(os.getcwd(),'software_skills.csv')
dfSoftwareSkills = pd.read_csv(filename1, header=0)

In [199]:
dfSoftwareSkills.head()

,O*NET-SOC Code,Title,Workplace Example,Element ID,Element Name,Hot Technology,In Demand
0,11-1011.00,Chief Executives,Adobe Acrobat,2.E.5.b,Document management software,Y,N
1,11-1011.00,Chief Executives,AdSense Tracker,2.E.6.f,Data base user interface and query software,N,N
2,11-1011.00,Chief Executives,Atlassian JIRA,2.E.5.a,Content workflow software,Y,N
3,11-1011.00,Chief Executives,Blackbaud The Raiser's Edge,2.E.6.c,Customer relationship management CRM software,N,N
4,11-1011.00,Chief Executives,ComputerEase construction accounting software,2.E.2.a,Accounting software,N,N

In [200]:
filename2 = os.path.join(os.getcwd(),'transferable_skills.csv')
dfTransferableSkills = pd.read_csv(filename2, header=0)

In [201]:
dfTransferableSkills.head(50)

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.B.1.a,Social Perceptiveness,IM,Importance,4.12,8,0.1250,3.8800,4.3700,N,NaN,08/2023,Analyst
1,11-1011.00,Chief Executives,2.B.1.a,Social Perceptiveness,LV,Level,4.25,8,0.1637,3.9292,4.5708,N,N,08/2023,Analyst
2,11-1011.00,Chief Executives,2.B.1.b,Coordination,IM,Importance,4.25,8,0.1637,3.9292,4.5708,N,NaN,08/2023,Analyst
3,11-1011.00,Chief Executives,2.B.1.b,Coordination,LV,Level,4.88,8,0.2266,4.4309,5.3191,N,N,08/2023,Analyst
4,11-1011.00,Chief Executives,2.B.1.c,Persuasion,IM,Importance,4.00,8,0.1890,3.6296,4.3704,N,NaN,08/2023,Analyst
5,11-1011.00,Chief Executives,2.B.1.c,Persuasion,LV,Level,4.75,8,0.1637,4.4292,5.0708,N,N,08/2023,Analyst
6,11-1011.00,Chief Executives,2.B.1.d,Negotiation,IM,Importance,4.12,8,0.1250,3.8800,4.3700,N,NaN,08/2023,Analyst
7,11-1011.00,Chief Executives,2.B.1.d,Negotiation,LV,Level,4.75,8,0.1637,4.4292,5.0708,N,N,08/2023,Analyst
8,11-1011.00,Chief Executives,2.B.1.e,Instructing,IM,Importance,3.38,8,0.1830,3.0164,3.7336,N,NaN,08/2023,Analyst
9,11-1011.00,Chief Executives,2.B.1.e,Instructing,LV,Level,3.88,8,0.1250,3.6300,4.1200,N,N,08/2023,Analyst
10,11-1011.00,Chief Executives,2.B.1.f,Service Orientation,IM,Importance,3.12,8,0.1250,2.8800,3.3700,N,NaN,08/2023,Analyst
11,11-1011.00,Chief Executives,2.B.1.f,Service Orientation,LV,Level,3.38,8,0.1830,3.0164,3.7336,N,N,08/2023,Analyst
12,11-1011.00,Chief Executives,2.B.2.i,Complex Problem Solving,IM,Importance,4.38,8,0.1830,4.0164,4.7336,N,NaN,08/2023,Analyst
13,11-1011.00,Chief Executives,2.B.2.i,Complex Problem Solving,LV,Level,4.88,8,0.1250,4.6300,5.1200,N,N,08/2023,Analyst
14,11-1011.00,Chief Executives,2.B.3.a,Operations Analysis,IM,Importance,3.12,8,0.1250,2.8800,3.3700,N,NaN,08/2023,Analyst
15,11-1011.00,Chief Executives,2.B.3.a,Operations Analysis,LV,Level,3.88,8,0.1250,3.6300,4.1200,N,N,08/2023,Analyst
16,11-1011.00,Chief Executives,2.B.3.b,Technology Design,IM,Importance,1.75,8,0.1637,1.4292,2.0708,N,NaN,08/2023,Analyst
17,11-1011.00,Chief Executives,2.B.3.b,Technology Design,LV,Level,0.88,8,0.2266,0.4309,1.3191,N,N,08/2023,Analyst
18,11-1011.00,Chief Executives,2.B.3.c,Equipment Selection,IM,Importance,1.12,8,0.1250,1.0000,1.3700,N,NaN,08/2023,Analyst
19,11-1011.00,Chief Executives,2.B.3.c,Equipment Selection,LV,Level,0.25,8,0.2500,0.0000,0.7400,N,Y,08/2023,Analyst
20,11-1011.00,Chief Executives,2.B.3.d,Installation,IM,Importance,1.00,8,0.0000,1.0000,1.0000,N,NaN,08/2023,Analyst
21,11-1011.00,Chief Executives,2.B.3.d,Installation,LV,Level,0.00,8,0.0000,0.0000,0.0000,N,Y,08/2023,Analyst
22,11-1011.00,Chief Executives,2.B.3.e,Programming,IM,Importance,1.75,8,0.1637,1.4292,2.0708,N,NaN,08/2023,Analyst
23,11-1011.00,Chief Executives,2.B.3.e,Programming,LV,Level,1.00,8,0.2673,0.4762,1.5238,N,N,08/2023,Analyst
24,11-1011.00,Chief Executives,2.B.3.g,Operations Monitoring,IM,Importance,2.00,8,0.1890,1.6296,2.3704,N,NaN,08/2023,Analyst
25,11-1011.00,Chief Executives,2.B.3.g,Operations Monitoring,LV,Level,1.50,8,0.3273,0.8584,2.1416,N,N,08/2023,Analyst
26,11-1011.00,Chief Executives,2.B.3.h,Operation and Control,IM,Importance,1.88,8,0.1250,1.6300,2.1200,N,NaN,08/2023,Analyst
27,11-1011.00,Chief Executives,2.B.3.h,Operation and Control,LV,Level,1.38,8,0.2631,0.8594,1.8906,N,N,08/2023,Analyst
28,11-1011.00,Chief Executives,2.B.3.j,Equipment Maintenance,IM,Importance,1.00,8,0.0000,1.0000,1.0000,N,NaN,08/2023,Analyst
29,11-1011.00,Chief Executives,2.B.3.j,Equipment Maintenance,LV,Level,0.00,8,0.0000,0.0000,0.0000,N,Y,08/2023,Analyst
30,11-1011.00,Chief Executives,2.B.3.k,Troubleshooting,IM,Importance,1.50,8,0.1890,1.1296,1.8704,N,NaN,08/2023,Analyst
31,11-1011.00,Chief Executives,2.B.3.k,Troubleshooting,LV,Level,0.50,8,0.1890,0.1296,0.8704,N,N,08/2023,Analyst
32,11-1011.00,Chief Executives,2.B.3.l,Repairing,IM,Importance,1.00,8,0.0000,1.0000,1.0000,N,NaN,08/2023,Analyst
33,11-1011.00,Chief Executives,2.B.3.l,Repairing,LV,Level,0.00,8,0.0000,0.0000,0.0000,N,Y,08/2023,Analyst
34,11-1011.00,Chief Executives,2.B.3.m,Quality Control Analysis,IM,Importance,1.88,8,0.1250,1.6300,2.1200,N,NaN,08/2023,Analyst
35,11-1011.00,Chief Executives,2.B.3.m,Quality Control Analysis,LV,Level,1.12,8,0.2266,0.6809,1.5691,N,N,08/2023,Analyst
36,11-1011.00,Chief Executives,2.B.4.e,Judgment and Decision Making,IM,Importance,4.75,8,0.1637,4.4292,5.0000,N,NaN,08/2023,Analyst
37,11-1011.00,Chief Executives,2.B.4.e,Judgment and Decision Making,LV,Level,5.38,8,0.2631,4.8594,5.8906,N,N,08/2023,Analyst
38,11-1011.00,Chief Executives,2.B.4.g,Systems Analysis,IM,Importance,4.12,8,0.1250,3.8800,4.3700,N,NaN,08/2023,Analyst
39,11-1011.00,Chief Executives,2.B.4.g,Systems Analysis,LV,Level,5.12,8,0.2266,4.6809,5.5691,N,N,08/2023,Analyst
40,11-1011.00,Chief Executives,2.B.4.h,Systems Evaluation,IM,Importance,4.25,8,0.1637,3.9292,4.5708,N,NaN,08/2023,Analyst
41,11-1011.00,Chief Executives,2.B.4.h,Systems Evaluation,LV,Level,5.00,8,0.1890,4.6296,5.3704,N,N,08/2023,Analyst
42,11-1011.00,Chief Executives,2.B.5.a,Time Management,IM,Importance,4.00,8,0.0000,4.0000,4.0000,N,NaN,08/2023,Analyst
43,11-1011.00,Chief Executives,2.B.5.a,Time Management,LV,Level,4.75,8,0.1637,4.4292,5.0708,N,N,08/2023,Analyst
44,11-1011.00,Chief Executives,2.B.5.b,Management of Financial Resources,IM,Importance,4.25,8,0.1637,3.9292,4.5708,N,NaN,08/2023,Analyst
45,11-1011.00,Chief Executives,2.B.5.b,Management of Financial Resources,LV,Level,5.25,8,0.2500,4.7600,5.7400,N,N,08/2023,Analyst
46,11-1011.00,Chief Executives,2.B.5.c,Management of Material Resources,IM,Importance,4.00,8,0.0000,4.0000,4.0000,N,NaN,08/2023,Analyst
47,11-1011.00,Chief Executives,2.B.5.c,Management of Material Resources,LV,Level,4.75,8,0.1637,4.4292,5.0708,N,N,08/2023,Analyst
48,11-1011.00,Chief Executives,2.B.5.d,Management of Personnel Resources,IM,Importance,4.25,8,0.1637,3.9292,4.5708,N,NaN,08/2023,Analyst
49,11-1011.00,Chief Executives,2.B.5.d,Management of Personnel Resources,LV,Level,5.25,8,0.2500,4.7600,5.7400,N,N,08/2023,Analyst

# Check for missing values

In [202]:
nan_count= np.sum(dfSoftwareSkills.isnull(), axis=0)
nan_count

O*NET-SOC Code       0
Title                0
Workplace Example    0
Element ID           0
Element Name         0
Hot Technology       0
In Demand            0
dtype: int64

In [203]:
nan_count= np.sum(dfTransferableSkills.isnull(), axis=0)
nan_count

O*NET-SOC Code            0
Title                     0
Element ID                0
Element Name              0
Scale ID                  0
Scale Name                0
Data Value                0
N                         0
Standard Error            0
Lower CI Bound            0
Upper CI Bound            0
Recommend Suppress        0
Not Relevant          22750
Date                      0
Domain Source             0
dtype: int64

# Dealing only with the Transferable skills data

## Drop rows and that have a val of Y in the Recomend Suppress col

In [204]:
dfTransferableSkills['Recommend Suppress'].unique()

array(['N', 'Y'], dtype=object)

In [205]:
count = (dfTransferableSkills['Recommend Suppress'] == 'Y').sum()
print(count)

136

In [206]:
dfTransferableSkills = dfTransferableSkills.drop(dfTransferableSkills[dfTransferableSkills['Recommend Suppress'] == 'Y'].index)

In [207]:
count = (dfTransferableSkills['Recommend Suppress']== 'Y').sum()
print(count)

0

In [208]:
dfTransferableSkills['Recommend Suppress'].unique()

array(['N'], dtype=object)

 ## Drop rows and that have a val of Y in the Not Relevant col

In [209]:
dfTransferableSkills['Not Relevant'].unique()

array([nan, 'N', 'Y'], dtype=object)

In [210]:
count = (dfTransferableSkills['Not Relevant']== 'Y').sum()
print(count)

3207

In [211]:
dfTransferableSkills = dfTransferableSkills.drop(dfTransferableSkills[dfTransferableSkills['Not Relevant'] == 'Y'].index)

In [212]:
count = (dfTransferableSkills['Not Relevant']== 'Y').sum()
print(count)

0

## Drop rows with a scale name of level

In [213]:
dfTransferableSkills = dfTransferableSkills.drop(dfTransferableSkills[dfTransferableSkills['Scale Name'] == 'Level'].index)

## Droping Columns

In [214]:
dfTransferableSkills.drop(columns=["Not Relevant", "Recommend Suppress", "Standard Error", "Lower CI Bound", "Upper CI Bound", "Date", "Domain Source", "N", "Element ID", "Scale ID"], inplace=True)

In [215]:
dfTransferableSkills.head(50)

,O*NET-SOC Code,Title,Element Name,Scale Name,Data Value
0,11-1011.00,Chief Executives,Social Perceptiveness,Importance,4.12
2,11-1011.00,Chief Executives,Coordination,Importance,4.25
4,11-1011.00,Chief Executives,Persuasion,Importance,4.00
6,11-1011.00,Chief Executives,Negotiation,Importance,4.12
8,11-1011.00,Chief Executives,Instructing,Importance,3.38
10,11-1011.00,Chief Executives,Service Orientation,Importance,3.12
12,11-1011.00,Chief Executives,Complex Problem Solving,Importance,4.38
14,11-1011.00,Chief Executives,Operations Analysis,Importance,3.12
16,11-1011.00,Chief Executives,Technology Design,Importance,1.75
18,11-1011.00,Chief Executives,Equipment Selection,Importance,1.12
20,11-1011.00,Chief Executives,Installation,Importance,1.00
22,11-1011.00,Chief Executives,Programming,Importance,1.75
24,11-1011.00,Chief Executives,Operations Monitoring,Importance,2.00
26,11-1011.00,Chief Executives,Operation and Control,Importance,1.88
28,11-1011.00,Chief Executives,Equipment Maintenance,Importance,1.00
30,11-1011.00,Chief Executives,Troubleshooting,Importance,1.50
32,11-1011.00,Chief Executives,Repairing,Importance,1.00
34,11-1011.00,Chief Executives,Quality Control Analysis,Importance,1.88
36,11-1011.00,Chief Executives,Judgment and Decision Making,Importance,4.75
38,11-1011.00,Chief Executives,Systems Analysis,Importance,4.12
40,11-1011.00,Chief Executives,Systems Evaluation,Importance,4.25
42,11-1011.00,Chief Executives,Time Management,Importance,4.00
44,11-1011.00,Chief Executives,Management of Financial Resources,Importance,4.25
46,11-1011.00,Chief Executives,Management of Material Resources,Importance,4.00
48,11-1011.00,Chief Executives,Management of Personnel Resources,Importance,4.25
50,11-1011.03,Chief Sustainability Officers,Social Perceptiveness,Importance,3.88
52,11-1011.03,Chief Sustainability Officers,Coordination,Importance,3.75
54,11-1011.03,Chief Sustainability Officers,Persuasion,Importance,3.88
56,11-1011.03,Chief Sustainability Officers,Negotiation,Importance,3.12
58,11-1011.03,Chief Sustainability Officers,Instructing,Importance,3.25
60,11-1011.03,Chief Sustainability Officers,Service Orientation,Importance,3.25
62,11-1011.03,Chief Sustainability Officers,Complex Problem Solving,Importance,4.00
64,11-1011.03,Chief Sustainability Officers,Operations Analysis,Importance,2.88
66,11-1011.03,Chief Sustainability Officers,Technology Design,Importance,1.88
68,11-1011.03,Chief Sustainability Officers,Equipment Selection,Importance,1.12
70,11-1011.03,Chief Sustainability Officers,Installation,Importance,1.00
72,11-1011.03,Chief Sustainability Officers,Programming,Importance,1.88
74,11-1011.03,Chief Sustainability Officers,Operations Monitoring,Importance,2.00
76,11-1011.03,Chief Sustainability Officers,Operation and Control,Importance,2.00
78,11-1011.03,Chief Sustainability Officers,Equipment Maintenance,Importance,1.00
80,11-1011.03,Chief Sustainability Officers,Troubleshooting,Importance,1.00
82,11-1011.03,Chief Sustainability Officers,Repairing,Importance,1.00
84,11-1011.03,Chief Sustainability Officers,Quality Control Analysis,Importance,1.88
86,11-1011.03,Chief Sustainability Officers,Judgment and Decision Making,Importance,3.88
88,11-1011.03,Chief Sustainability Officers,Systems Analysis,Importance,3.88
90,11-1011.03,Chief Sustainability Officers,Systems Evaluation,Importance,3.88
92,11-1011.03,Chief Sustainability Officers,Time Management,Importance,3.38
94,11-1011.03,Chief Sustainability Officers,Management of Financial Resources,Importance,2.88
96,11-1011.03,Chief Sustainability Officers,Management of Material Resources,Importance,2.25
98,11-1011.03,Chief Sustainability Officers,Management of Personnel Resources,Importance,3.12

## rename Data value to importance

## drop Scal name col

# drop stuff in other dataset

# combine stuff